version: '2'
services:
  control:
    container_name: jepsen-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    mem_limit: 32g
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
    # Uncomment 'volumes' for dev. This helps in that:
    # - It precludes from downloading the web for maven dependencies
    # - It allows to use locally built versions of libs
    # - Changes to jepsen are automatically available in the jepsen-control
    #   container and test results are automatically available in the host. 
    volumes:
      - ~/.m2:/root/.m2
      - ../:/jepsen
  node:
    container_name: node
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  m1:
    extends: node
    container_name: jepsen-m1
    hostname: m1
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
